name: thesis-scripts
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.3.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2022.5.18.1
  - certifi=2022.5.18.1
  - cycler=0.11.0
  - ffmpeg=5.0.1q
  - ffmpeg-python=0.2.0
  - fonttools=4.33.3
  - freetype=2.10.4
  - future=0.18.2
  - gettext=0.19.8.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.7.6
  - icu=70.1
  - imagehash=4.2.1
  - jpeg=9e
  - kiwisolver=1.4.3
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libcxx=14.0.5
  - libdeflate=1.12
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=9.3.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - libopenblas=0.3.20
  - libpng=1.6.37
  - libtasn1=4.18.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libvpx=1.11.0
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.13
  - libxml2=2.9.14
  - libzlib=1.2.12
  - llvm-openmp=14.0.4
  - lz4-c=1.9.3
  - matplotlib=3.5.2
  - matplotlib-base=3.5.2
  - munkres=1.1.4
  - ncurses=6.3
  - nettle=3.8
  - numpy=1.22.4
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=3.0.3
  - p11-kit=0.24.1
  - packaging=21.3
  - pandas=1.4.2
  - pillow=9.1.1
  - pip=22.1.2
  - pthread-stubs=0.4
  - pyparsing=3.0.9
  - python=3.9.13
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pytz=2022.1
  - pywavelets=1.3.0
  - readline=8.1.2
  - scipy=1.8.1
  - setuptools=62.3.4
  - six=1.16.0
  - sqlite=3.38.5
  - svt-av1=1.1.0
  - tk=8.6.12
  - tornado=6.1
  - tzdata=2022a
  - unicodedata2=14.0.0
  - wheel=0.37.1
  - x264=1!161.3030
  - x265=3.5
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - zlib=1.2.12
  - zstd=1.5.2
