version: '3.8'
services:
  redis:
    build: ./redis
    container_name: 'redis-stack'
    restart: always
    volumes:
      - ./redis/redis-stack-server.conf:/opt/redis-stack/etc/redis-stack.conf
      - ./redis/dump.rdb:/data/dump.rdb
    ports:
      - "6379:6379"
  newssum:
    build: ./newssum
    container_name: 'newssum'
    command: [ "python3", "-u", "nsum_training.py",
               "--token_to_word_path", "/home/s3d/dict.npy",
               "--pretrain_cnn_path", "/home/s3d/s3d_howto100m.pth",
               "--out_path", "/home/out",
               "--dataset_path", "/home/TS",
               "--num_thread_reader", "0",
               "--batch_size", "4", "--batch_size_eval", "4",
               "--heads", "4", "--enc_layers", "12",
               "--lrv", "0.00001", "--lrs", "0.00001"]
    volumes:
      - /Users/tihmels/TS/:/home/TS/
    depends_on:
      - redis
    environment:
      - REDIS_HOST=host.docker.internal
      - REDIS_PORT=6379


