version: '3.8'
services:
  redis:
    volumes:
      - ./redis/redis-stack-server.conf:/opt/redis-stack/etc/redis-stack.conf
      - /home/ma-newssum/redis/dump.rdb:/data/dump.rdb
  newssum:
    tty: true
    command: [ "python3", "-u", "nsum_training.py",
               "--token_to_word_path", "/home/s3d/dict.npy",
               "--pretrain_cnn_path", "/home/s3d/s3d_howto100m.pth",
               "--out_path", "/home/out",
               "--dataset_path", "/home/ma-newssum/TS",
               "--num_thread_reader", "0",
               "--epochs", "30", "--batch_size", "4", "--batch_size_eval", "4",
               "--heads", "8", "--enc_layers", "24",
               "--weight_decay", "0.00001", "--dropout", "0.1",
               "--num_frames_per_segment", "16",
               "--fps", "8", "--num_frames", "480",
               "--lrv", "0.001", "--lrs", "0.0001",
               "--log_freq", "5",
               "--finetune"]
    volumes:
      - /home/ma-newssum/TS/ts15/:/home/TS/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


