version: '3.8'
services:
  redis:
    volumes:
      - /home/ma-newssum/redis/dump.rdb:/data/dump.rdb
  newssum:
    command: [ "python3", "-u", "nsum_training.py",
               "--model_type", "1",
               "--token_to_word_path", "/home/s3d/dict.npy",
               "--pretrain_cnn_path", "/home/s3d/s3d_howto100m.pth",
               "--out_path", "/home/out",
               "--dataset_path", "/home/TS",
               "--num_thread_reader", "0",
               "--epochs", "30", "--batch_size", "16", "--batch_size_eval", "16",
               "--heads", "8", "--enc_layers", "24",
               "--lrv", "0.00001", "--lrs", "0.00001",
               "--weight_decay", "0.00001", "--dropout", "0.1",
               "--num_frames_per_segment", "16",
               "--fps", "8", "--num_frames", "480",
               "--log_freq", "3"]
    volumes:
      - /home/ma-newssum/TS/:/home/TS/
      - /home/ma-newssum/out/:/home/out
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379


